// Code generated by mockery v2.2.1. DO NOT EDIT.

package service

import (
	model "HotelAutomation/model"

	mock "github.com/stretchr/testify/mock"

	service "HotelAutomation/service"
)

// HotelServiceI is an autogenerated mock type for the HotelServiceI type
type HotelServiceI struct {
	mock.Mock
}

// CreateHotel provides a mock function with given fields: request
func (_m *HotelServiceI) CreateHotel(request service.CreateHotelRequest) {
	_m.Called(request)
}

// GetAppliances provides a mock function with given fields:
func (_m *HotelServiceI) GetAppliances() []service.Appliances {
	ret := _m.Called()

	var r0 []service.Appliances
	if rf, ok := ret.Get(0).(func() []service.Appliances); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Appliances)
		}
	}

	return r0
}

// GetAppliancesInfo provides a mock function with given fields:
func (_m *HotelServiceI) GetAppliancesInfo() []service.AppliancesInfo {
	ret := _m.Called()

	var r0 []service.AppliancesInfo
	if rf, ok := ret.Get(0).(func() []service.AppliancesInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.AppliancesInfo)
		}
	}

	return r0
}

// GetNumberOfCorridors provides a mock function with given fields: corridorType
func (_m *HotelServiceI) GetNumberOfCorridors(floorNumber int, corridorType model.CorridorType) int {
	ret := _m.Called(corridorType)

	var r0 int
	if rf, ok := ret.Get(0).(func(model.CorridorType) int); ok {
		r0 = rf(corridorType)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
