// Code generated by mockery v2.2.1. DO NOT EDIT.

package service

import (
	service "HotelAutomation/service"

	mock "github.com/stretchr/testify/mock"
)

// ObserverI is an autogenerated mock type for the ObserverI type
type ObserverI struct {
	mock.Mock
}

// Update provides a mock function with given fields: _a0
func (_m *ObserverI) Update(_a0 service.ToggleApplianceRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(service.ToggleApplianceRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
