// Code generated by mockery v2.2.1. DO NOT EDIT.

package service

import (
	service "HotelAutomation/service"

	mock "github.com/stretchr/testify/mock"
)

// PowerControllerServiceI is an autogenerated mock type for the PowerControllerServiceI type
type PowerControllerServiceI struct {
	mock.Mock
}

// RegisterDevices provides a mock function with given fields:
func (_m *PowerControllerServiceI) RegisterDevices() {
	_m.Called()
}

// TotalPowerConsumptionAtFloor provides a mock function with given fields: floorNumber
func (_m *PowerControllerServiceI) TotalPowerConsumptionAtFloor(floorNumber int) int {
	ret := _m.Called(floorNumber)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(floorNumber)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Update provides a mock function with given fields: request
func (_m *PowerControllerServiceI) Update(request service.ToggleApplianceRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(service.ToggleApplianceRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
