// Code generated by mockery v2.2.1. DO NOT EDIT.

package service

import (
	appliances "HotelAutomation/model/appliances"

	mock "github.com/stretchr/testify/mock"

	model "HotelAutomation/model"

	service "HotelAutomation/service"
)

// PowerControllerServiceI is an autogenerated mock type for the PowerControllerServiceI type
type PowerControllerServiceI struct {
	mock.Mock
}

// RegisterDevices provides a mock function with given fields:
func (_m *PowerControllerServiceI) RegisterDevices() {
	_m.Called()
}

// ToggleApplianceToReverseState provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *PowerControllerServiceI) ToggleApplianceToReverseState(_a0 int, _a1 model.CorridorType, _a2 appliances.ApplianceType, _a3 bool) {
	_m.Called(_a0, _a1, _a2, _a3)
}

// TotalPowerConsumptionAtFloor provides a mock function with given fields: _a0
func (_m *PowerControllerServiceI) TotalPowerConsumptionAtFloor(_a0 int) int {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *PowerControllerServiceI) Update(_a0 service.ToggleApplianceRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(service.ToggleApplianceRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
